
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.0
 * Query Engine version: ab56fe763f921d033a6c195e7ddeb3e255bdbb57
 */
Prisma.prismaVersion = {
  client: "7.4.0",
  engine: "ab56fe763f921d033a6c195e7ddeb3e255bdbb57"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.DistrictScalarFieldEnum = {
  id: 'id',
  name: 'name',
  isCapital: 'isCapital',
  createdAt: 'createdAt'
};

exports.Prisma.CaseRequestScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  amount: 'amount',
  category: 'category',
  districtId: 'districtId',
  documents: 'documents',
  status: 'status',
  submittedAt: 'submittedAt',
  adoptedByNgoId: 'adoptedByNgoId',
  campaignId: 'campaignId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  role: 'role',
  ngoId: 'ngoId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NgoScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameUrdu: 'nameUrdu',
  registrationNumber: 'registrationNumber',
  districtId: 'districtId',
  categories: 'categories',
  email: 'email',
  phone: 'phone',
  address: 'address',
  website: 'website',
  bankAccount: 'bankAccount',
  ifsc: 'ifsc',
  accountHolder: 'accountHolder',
  bankName: 'bankName',
  upiId: 'upiId',
  status: 'status',
  rejectionReason: 'rejectionReason',
  documents: 'documents',
  createdAt: 'createdAt',
  verifiedAt: 'verifiedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CampaignScalarFieldEnum = {
  id: 'id',
  ngoId: 'ngoId',
  title: 'title',
  description: 'description',
  category: 'category',
  goalAmount: 'goalAmount',
  verifiedAmount: 'verifiedAmount',
  pendingAmount: 'pendingAmount',
  deadline: 'deadline',
  imageUrl: 'imageUrl',
  upiId: 'upiId',
  bankAccount: 'bankAccount',
  ifsc: 'ifsc',
  accountHolder: 'accountHolder',
  bankName: 'bankName',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  closedAt: 'closedAt'
};

exports.Prisma.DonationScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  donorName: 'donorName',
  amount: 'amount',
  utrLast4: 'utrLast4',
  paymentTime: 'paymentTime',
  screenshotUrl: 'screenshotUrl',
  status: 'status',
  verifiedAt: 'verifiedAt',
  reportedAt: 'reportedAt'
};

exports.Prisma.CampaignUpdateScalarFieldEnum = {
  id: 'id',
  campaignId: 'campaignId',
  ngoId: 'ngoId',
  content: 'content',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.Category = exports.$Enums.Category = {
  MEDICAL: 'MEDICAL',
  EDUCATION: 'EDUCATION',
  DISASTER: 'DISASTER',
  WOMEN: 'WOMEN',
  ORPHAN: 'ORPHAN',
  LIVELIHOOD: 'LIVELIHOOD',
  ENVIRONMENT: 'ENVIRONMENT'
};

exports.CaseStatus = exports.$Enums.CaseStatus = {
  AVAILABLE: 'AVAILABLE',
  ADOPTED: 'ADOPTED',
  REJECTED: 'REJECTED'
};

exports.UserRole = exports.$Enums.UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  NGO_PARTNER: 'NGO_PARTNER'
};

exports.NgoStatus = exports.$Enums.NgoStatus = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
};

exports.CampaignStatus = exports.$Enums.CampaignStatus = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  ACTIVE: 'ACTIVE',
  URGENT: 'URGENT',
  GOAL_MET: 'GOAL_MET',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED'
};

exports.DonationStatus = exports.$Enums.DonationStatus = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  FLAGGED: 'FLAGGED'
};

exports.Prisma.ModelName = {
  District: 'District',
  CaseRequest: 'CaseRequest',
  User: 'User',
  Ngo: 'Ngo',
  Campaign: 'Campaign',
  Donation: 'Donation',
  CampaignUpdate: 'CampaignUpdate'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
